In [55]:
import numpy as np

### 0 - D

In [58]:
a = 45
print(a)
print(type(a))

45
<class 'int'>


In [60]:
a = 45 
arr_0 = np.array(a)
print(a)
print(type(arr_0))

45
<class 'numpy.ndarray'>


In [62]:
arr_0.ndim

0

In [64]:
arr_0.shape

()

### 1 - D

In [67]:
a = [1,2,3]
arr_1 = np.array(a)
print(arr_2)

[[1 2 3]]


In [69]:
arr_1.ndim

1

In [71]:
arr_1.shape

(3,)

### 2 - D

In [74]:
a = [[1,2,3]]
arr_2 = np.array(a)
print(arr_2)

[[1 2 3]]


In [76]:
arr_2.ndim

2

In [78]:
arr_2.shape

(1, 3)

## Functions for creating 1D array

In [93]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [117]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [213]:
np.zeros((2,))

array([0., 0.])

In [215]:
np.ones((2,))


array([1., 1.])

In [219]:
np.random.randint(1,1000,5)

array([720, 612, 183, 969, 379])

## Acessing elements/extracting the values

In [121]:
a = np.arange(10,51,10)
print(a)

[10 20 30 40 50]


In [123]:
a[1]

20

In [125]:
a[-1]

50

In [127]:
a[1:5:2]

array([20, 40])

In [131]:
a[-1:-5:-2]

array([50, 30])

In [137]:
a[[0,3,2,4]]

array([10, 40, 30, 50])

In [139]:
a = np.array([45,46,47])

a[a%2 == 0]

array([46])

Modify the Values in Numpy


In [147]:
a = np.array([45,46,47])

a1 = np.append(a,110)
print(a1)

[ 45  46  47 110]


In [151]:
a = np.array([45,46,110])

a2 = np.append(a,[110,123,120])
print(a2)

[ 45  46 110 110 123 120]


In [153]:
a[0] = 150
print(a)

[150  46 110]


In [155]:
a[[1,2]] = 15
a

array([150,  15,  15])

In [159]:
a[[1,2]] = [460,14]
a

array([150, 460,  14])

In [161]:
a3 = np.delete(a,1)
print(a3)

[150  14]


In [169]:
a4 = np.delete(a,[1,2])
print(a4)
a4

[150]


array([150])

In [171]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [173]:
a = np.array([4,6,8,2,1])

b = np.sort(a)
print(b)

[1 2 4 6 8]


OPERATIONS

In [175]:
a = np.array([1,2,3,4])

In [177]:
b = a+1
print(b)

[2 3 4 5]


In [179]:
c = a+0
print(c)

[1 2 3 4]


In [183]:
d = a**2
print(d)

[ 1  4  9 16]


In [185]:
print(a+b)

[3 5 7 9]


In [189]:
print(a)
print(b)
print(a-b)

[1 2 3 4]
[2 3 4 5]
[-1 -1 -1 -1]


In [193]:
print(a*b)

[ 2  6 12 20]


## comparison operator

In [197]:
print(a)
print(c)
a == c

[1 2 3 4]
[1 2 3 4]


array([ True,  True,  True,  True])

In [199]:
c >= a

array([ True,  True,  True,  True])

In [201]:
np.array_equal(a,b)

False

In [222]:
np.array_equal(a,c)

True

### Mathematical operations

In [225]:
np.exp(a)


array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [227]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [231]:
import warnings
warnings.simplefilter("ignore")

### 2D Numpy Array

In [238]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [240]:
b.ndim

2

In [242]:
b.shape

(2, 4)

In [246]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [258]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [260]:
np.ones((3,3))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [262]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [264]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [270]:
a = np.array([[1,2,3],[3,4,5]])
np.diag(a)

array([1, 4])

In [274]:
a = np.array([[1,2,3],[3,4,5],[6,7,8]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

### indexing of 2D array

In [278]:
a[0]

array([1, 2, 3])

a[2,2]  #row,column

In [282]:
a[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [284]:
a[1] = [25,30,60]
a

array([[ 1,  2,  3],
       [25, 30, 60],
       [ 6,  7,  8]])

In [294]:
a[0,2] = 500
a

array([[  1,   2, 500],
       [ 25,  30,  60],
       [  6,   7,   8]])

In [298]:
a[:,2] = 0
a

array([[ 1,  2,  0],
       [25, 30,  0],
       [ 6,  7,  0]])

In [329]:
a[0:2,0:2] = 10
a

array([[10, 10,  1],
       [10, 10,  1],
       [ 0,  0,  0]])

#### flatening

In [332]:
a = np.array([[0,1,2],[3,4,5]])
print(a)

b = a.ravel()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


##### reshape array

In [341]:
arr = np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [343]:
a1 = arr.reshape(2,3)
print(a1)

[[0 1 2]
 [3 4 5]]


In [347]:
a = np.array([[0,1,5],[10,50,8]])
print(a)
print(a.shape)

[[ 0  1  5]
 [10 50  8]]
(2, 3)


In [349]:
print(a.reshape(3,2))

[[ 0  1]
 [ 5 10]
 [50  8]]


In [361]:
c = a.T
print(a)
print("after transpose")
print(c)

[[ 0  1  5]
 [10 50  8]]
after transpose
[[ 0 10]
 [ 1 50]
 [ 5  8]]


#### sort

In [380]:
# axis = 1 --> row and axis = 0 -->column
a = np.array([[5,4,6],[2,8,2],[8,9,20]])
b = np.sort(a,axis = 0)
print(b,"axis = 0")
print(" ")
c = np.sort(a,axis = 1)
print(c,"axis = 1")

[[ 2  4  2]
 [ 5  8  6]
 [ 8  9 20]] axis = 0
 
[[ 4  5  6]
 [ 2  2  8]
 [ 8  9 20]] axis = 1


In [386]:
a = np.array([[5,4,6],[2,8,2],[8,9,20]])
b = np.array([[0,1,5],[10,50,8],[1,2,3]])
print(a+b)

[[ 5  5 11]
 [12 58 10]
 [ 9 11 23]]


In [388]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [392]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [410]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [414]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [416]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [418]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])