In [ ]:
pip install opencv-python

In [1]:
import cv2

In [2]:
cv2.__version__

'4.11.0'

In [3]:
import numpy as np

In [4]:
img = cv2.imread('image_examples/Modi.jpg',1)

In [5]:
cv2.imshow('PM',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [7]:
type(img)

numpy.ndarray

In [8]:
img.ndim

3

In [9]:
img.shape

(1358, 1500, 3)

In [10]:
img = cv2.imread('image_examples/Modi.jpg',1)
resized_image = cv2.resize(img,(679,750))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow('PM',gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
cv2.imwrite('bw.jpg',gray)

True

In [12]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

In [13]:
faces = face_classifier.detectMultiScale(gray, 1.5, 5)

In [14]:
faces

array([[292, 145, 273, 273]])

In [15]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

image = cv2.imread('image_examples/Modi.jpg',1)
image = cv2.resize(image,(679,750))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray, 1.5, 5)

if faces is ():
    print('No face found')
else:
    for  (x,y,l,h) in faces:
        cv2.rectangle(image, (x,y), (x+l,y+h), (255,0,255), 1)

cv2.imshow('Face Detection',image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:9: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:9: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\kawle\AppData\Local\Temp\ipykernel_23432\2365965237.py:9: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is ():


In [ ]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

img = cv2.imread('image_examples/Modi.jpg')
resized_image = cv2.resize(img,(679,750))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.05,5)

if faces is ():
    print('No face found')

for(x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resized_image[y:y+h, x:x+w]

    eyes = eye_classifier.detectMultiScale(roi_gray,1.05,5)
    for  (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),1)

cv2.imshow('img',resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
import cv2
video = cv2.VideoCapture(0)

while True:
    num,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('video',gray)
    if cv2.waitKey(1) == ('q'):
        break

video.release()
cv2.destroyAllWindows()

error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [19]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

def detect(gray,frame):
        faces = face_classifier.detectMultiScale(gray,1.05,5)

        if faces is ():
            print('No face found')

        for(x,y,w,h) in faces:
            cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
            roi_gray = gray[y:y+h, x:x+w]
            roi_color = resized_image[y:y+h, x:x+w]

            eyes = eye_classifier.detectMultiScale(roi_gray,1.05,5)
            for  (ex,ey,ew,eh) in eyes:
                cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),1)
        return frame

video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('video',frame)
    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

<>:7: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:7: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\kawle\AppData\Local\Temp\ipykernel_23432\890534435.py:7: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is ():


error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [24]:
import cv2

body_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_fullbody.xml')

cap = cv2.VideoCapture('image_examples/walking.avi')

while cap.isOpened():
    check,frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies = body_classifier.detectMultiScale(gray,1.2,3)

    for (x,y,w,h) in bodies:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,255), 2)
        cv2.imshow('Pedestrians',frame)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [29]:
import time

car_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_car.xml')
cap = cv2.VideoCapture('image_examples/cars.avi')

while cap.isOpened():

    time.sleep(.01)
    check,frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cars = car_classifier.detectMultiScale(gray,1.4,2)
    for (x,y,w,h) in cars:
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,255), 2)
        cv2.imshow('cars',frame)

    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()